### ISSUE TITLE
No longer required to modify Truffle config to find .ts files

### ISSUE THREAD

**Issue by pcowgill** [ethereum-ts/truffle-typechain-example#5]
In the `truffle-typechain-example` README it says,

```javascript
// this is required by truffle to find any ts test files
test_file_extension_regexp: /.*\.ts$/,
```

But from the Truffle docs, `Truffle now supports tests saved as a .ts TypeScript file.` ([Source](https://www.trufflesuite.com/docs/truffle/testing/writing-tests-in-javascript#typescript-file-support))

So I think that `Tweak truffle.js` step can be removed that from the README, right?

**Comment by krzkaczor** [comment]
@pcowgill thanks for bringing up this issue to my attention. I think that first of all we need to upgrade truffle to @5. I will leave this issue open for now. 

If you want to work on upgrading this project just let me know :)

**Comment by pcowgill** [comment]
I suppose since some folks are still on Truffle 4, it would be ideal to keep the step in, noting that it only applies for Truffle 4.

I'll let you know if I have some bandwidth to work on this! Thanks!
